platform:ios,'8.0'
target 'Bluehelix' do
    pod 'SDWebImage', '~> 4.0.0'
    pod 'OpenSSL-Universal'
    pod 'MJExtension', '~> 3.0.13'
    pod 'Masonry', '~> 1.0.2'
    pod 'SocketRocket', '~> 0.5.1'
end

