platform:ios,'8.0'
target 'Bluehelix' do
    pod 'IQKeyboardManager', '~> 4.0.10'
    pod 'SDWebImage', '~> 4.0.0'
    pod 'OpenSSL-Universal'
    pod 'CBBase58'
    pod 'MJExtension', '~> 3.0.13'
    pod 'MJRefresh', '~> 3.1.12'
     pod 'MBProgressHUD+JDragon'
end

